myproject/core/urls.py
from django.urls import path
from myproject.core import views as c


app_name = 'core'
urlpatterns = [
    path('', c.home, name='home'),
    path('person/', c.PersonList.as_view(), name='person_list'),
    path('person/add/', c.person_create, name='person_add'),
    path('person/<int:pk>/', c.person_detail, name='person_detail'),
    path('person/<int:pk>/edit/', c.person_update, name='person_edit'),
    path('person/<int:pk>/delete/',
         c.person_delete, name='person_delete'),
    path('thread/', c.my_thread, name='thread'),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from localflavor.br.br_states import STATE_CHOICES

PHONE_TYPE = (
    ('pri', 'principal'),
    ('com', 'comercial'),
    ('res', 'residencial'),
    ('cel', 'celular'),
    ('cl', 'Claro'),
    ('oi', 'Oi'),
    ('t', 'Tim'),
    ('v', 'Vivo'),
    ('n', 'Nextel'),
    ('fax', 'fax'),
    ('o', 'outros'),
)


class TimeStampedModel(models.Model):
    created = models.DateTimeField('criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField('modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(u'endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2, choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel, Address):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField('sobrenome', max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    blocked = models.BooleanField('bloqueado', default=False)

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return ' '.join(filter(None, [self.first_name, self.last_name]))

    full_name = property(__str__)

    def get_absolute_url(self):
        return r('core:person_detail', pk=self.pk)


class Phone(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    person = models.ForeignKey('Person', on_delete=models.PROTECT)
    phone_type = models.CharField('tipo', max_length=3, choices=PHONE_TYPE, default='pri')

    def __str__(self):
        return self.phone

myproject/core/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email', 'address',
                  'complement', 'district', 'city', 'uf', 'cep', 'blocked']

myproject/core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy as r
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from .mixins import NameSearchMixin
from .models import Person
from .forms import PersonForm
from .my_thread import MyThread


def home(request):
    return render(request, 'index.html')


class PersonList(NameSearchMixin, ListView):
    model = Person
    paginate_by = 10


person_detail = DetailView.as_view(model=Person)

person_create = CreateView.as_view(model=Person, form_class=PersonForm)

person_update = UpdateView.as_view(model=Person, form_class=PersonForm)

person_delete = DeleteView.as_view(
    model=Person,
    success_url=r('core:person_list')
)


def my_thread(request):
    thread = MyThread()
    thread.start()
    msg = 'Start thread...'
    print(msg)
    return HttpResponseRedirect(reverse('core:home'))

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Django boilerplate">
  <meta name="author" content="rg3915">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

  <title>
    {% block title %}Django{% endblock title %}
  </title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/social.css" %}">
  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <style type="text/css">
    body {
      padding-top: 50px;
      /*color: #5a5a5a;*/
    }
  </style>

</head>
<body>
  {% include "nav.html" %}
  <div id="wrap">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>
  {% include "footer.html" %}
</body>
</html>

myproject/core/templates/core/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Person Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:person_list' %}">Contatos</a> <span class="divider"></span></li>
  <li class="active">{{ object.full_name }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
    <div class="social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      {% if object.phone_set.all %}
        {% for phone in object.phone_set.all %}
          <tr>
            <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
            <td>{{ phone.phone }} <i class="fa fa-whatsapp ok"></i> {{ phone.get_phone_type_display }}</td>
          </tr>
        {% endfor %}
      {% else %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
          <td>---</td>
        </tr>
      {% endif %}

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-map-marker"></span></th>
          <td>{{ object.address }}
            {% if object.complement %} - {{ object.complement }}{% endif %}
            {% if object.district %} - {{ object.district }}{% endif %}
          </td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"></th>
          <td>
            {% if object.city %}{{ object.city }}{% endif %}
            {% if object.uf %} - {{ object.uf }}{% endif %}
            {% if object.cep %} - {{ object.cep }}{% endif %}
          </td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Bloqueado</th>
          <td><span class="glyphicon {{ object.blocked|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:person_edit' person.pk %}">
      <button id="edit_person" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'core:person_delete' person.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

myproject/core/templates/core/person_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Person Form{% endblock title %}

{% block content %}

<div class="page-header">
    <h2>Novo Contato</h2>
</div>

<form class="form-horizontal" action="." method="POST">
    {% csrf_token %}
    {{ form.non_fields_errors }}
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.first_name.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.first_name|attr:"class:form-control" }} {{ form.first_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.last_name.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.last_name|attr:"class:form-control" }} {{ form.last_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.email.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.email|attr:"class:form-control" }} {{ form.email.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.address.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.address|attr:"class:form-control" }} {{ form.address.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.complement.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.complement|attr:"class:form-control" }} {{ form.complement.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.district.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.district|attr:"class:form-control" }} {{ form.district.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.city.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.city|attr:"class:form-control" }} {{ form.city.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.uf.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.uf|attr:"class:form-control" }} {{ form.uf.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.cep.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.cep|attr:"class:form-control" }} {{ form.cep.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.blocked.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.blocked }} {{ form.blocked.errors }}
        </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</form>

{% endblock content %}

myproject/core/templates/core/person_list.html
{% extends 'base.html' %}

{% block title %}Contatos{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url 'core:person_add' %}">
        <button id="new" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2><h2><i class="fa fa-user"></i> Lista de Contatos</h2>
</div>

<div>
{% if person_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>UF</th>
      </tr>
    </thead>
    <tbody>
    {% for person in person_list %}
      <tr>
        <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
        <td>{{ person.email }}</td>
        {% if person.phone_set.first %}
          <td>{{ person.phone_set.first }} 
            {% if person.phone_set.count > 1 %}
              <a href="{{ person.get_absolute_url }}">+{{ person.phone_set.count|add:"-1" }}</a>
            {% endif %}
          </td>
        {% else %}
          <td>---</td>
        {% endif %}
        <td>{{ person.get_uf_display }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} contato{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

myproject/core/templates/footer.html
<div id="footer">
  <div class="container">
    <p class="credit pull-left">Example by <a href="https://github.com/rg3915/">Régis da Silva</a> &copy; 2018 &middot; <a href="">download</a></p>
    <div class="socialfooter pull-center">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Bem vindo!</h1>
    <a href="{% url 'core:thread' %}">
      <button id="new_customer" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Thread
      </button>
    </a>
  </div>

{% endblock content %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'core:person_list' %}"><span class="fa fa-users"></span> Lista de Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="fa fa-drupal"></span> Admin</a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/pagination.html
<!-- pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% endif %}
      {% for pg in page_obj.paginator.page_range %}
        {% if page_obj.number == pg %}
          <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% else %}
          <li><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>
<!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->